# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:            Bunda Irna
tagline:          'Learning, Coding and Sharing.'
description:      'Blog of YourName. Here are some technical stuff. Some notes about development.'
url:              http://irnawansuprapti.github.io

author:
  name:           'Irnawan Suprapti'
  url:            http://irnawansuprapti.github.io
  gravatar:       https://en.gravatar.com/irnawansuprapti
  photo:          http://2.gravatar.com/avatar/00000000000000000000000000000000?size=350
  introduction:   'Some introduction words that will be displayed under the avatar. You may include HTML <a href="#">here</a>.'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/codinfox/lanyon-codinfox.github.io
