# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:            Agus
tagline:          'Learning, Coding and Sharing.'
description:      'Simple tools for.'
url:              http://irnawansuprapti.github.io

author:
  name:           'Agus Suhartono'
  url:            http://www.agus.pro
  gravatar:       https://en.gravatar.com/agussuhartono
  photo:          https://secure.gravatar.com/avatar/01eed2065469bcf386582acb1f0671c8
  introduction:   'Professioan Software Developer. CEO at <a href="http://www.binexa.com">Binexa Internet</a>. More about me <a href="/about">here</a>.'

paginate:         10
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/agussuhartono/agussuhartono.github.io
